### ISSUE TITLE
colorKey for Thumbnails view

### ISSUE THREAD

**Issue by jtoner** [simile-widgets/exhibit#138]
Hi
I cant get this to work. Any help or links to working model greatly appreciated.
Kind regards
J

**Comment by lmorillas** [comment]
http://simile-widgets.org/exhibit3/examples/nobelists/nobelists.html ? 

Where is your code?

**Comment by jtoner** [comment]
Sorry Imorillas. Many thanks for responding.

I was using the nobelist example to test it. Basically I wanted the div.nobelist-thumbnail background colour to reflect the colorkey, as in the timeline view in the same example. I wasn't sure it could be done. I see in other examples http://simile-widgets.org/exhibit3/examples/senate/senate.html they have had to use javascript for the table row colour. The standard method that works in the timeline/map view examples doesn't seem to work in the thumbnail view or am I missing something e.g data-ex-color-coder="party-colors" 

I recently found this example http://simile.mit.edu/projects.html which seems to work, although I haven't tried it yet, and is using an old version of exhibit.

**Comment by lmorillas** [comment]
I don't know if color-coders work with thumbnails. 

You can use CSS. With the nobelist example: 

```html
 <div ex:role="exhibit-lens" ex:class-subcontent="nobelist-thumbnail {{.discipline}}"  
    style="display: none;">
   ...
```
And use de lens class to backgound it .

**Comment by jtoner** [comment]
Sorry - really grateful for your help but struggling to make that work. are you able to show me what I should be adding where?

<html>
  <head>
    <title>SIMILE Widgets | Exhibit 3.0 | Examples | MIT Nobel Prize Winners</title>
    <link rel="stylesheet" href="http://www.simile-widgets.org/styles/common.css" type="text/css" />

    <link href="nobelists.js" type="application/json" rel="exhibit-data" />

    <link rel="exhibit-extension" type="text/javascript" href="http://api.simile-widgets.org/exhibit/3.1.0rc/extensions/time/time-extension.js" />

    <script src="http://api.simile-widgets.org/exhibit/3.1.0rc/exhibit-api.js"></script>
    
    
    <style>
        #main-content { background: white; }
        #title-panel { padding: 0.25in 0.5in; }
        #top-panels {
            padding:        0.5em 0.5in;
            border-top:     1px solid #BCB79E;
            border-bottom:  1px solid #BCB79E;
            background:     #FBF4D3;
        }
        
        .exhibit-tileView-body { list-style: none; }
        .exhibit-collectionView-group-count { display: none; }
        
        table.nobelist {
            border:     1px solid #ddd;
            padding:    0.5em;
        }
        div.name {
            font-weight: bold;
            font-size:   120%;
        }
        .relationship {
            color:  #888;
        }
        
        div.nobelist-thumbnail {
            float:      left;
            width:      13em;
            height:     10em;
            border:     1px solid #BCB79E;
            background: #F0FFF0;
            padding:    1em;
            margin:     0.5em;
            text-align: center;
        }
        div.nobelist-timeline-lens {
            padding:    1em;
            text-align: center;
        }
    </style>
    <script type="text/javascript">
        function deceaseRowStyler(itemID, database, tr, rowIndex) {
            var deceased = database.getObject(itemID, "deceased");
            if (deceased == "yes") {
                tr.style.backgroundColor = "#f88";
            }
        }
    </script>
  </head> 
  <body>
    <ul id="path">
      <li><a href="/">SIMILE Widgets</a></li>
      <li><a href="/exhibit3/">Exhibit 3.0</a></li>
      <li><span>Examples: MIT Nobel Prize Winners</span></li>
    </ul>
    
    <div id="main-content">
        <div id="title-panel">
            <h1>63 MIT-related Nobel Prize Winners</h1>
            <p>The information within this page has been retrieved from
                <a href="http://web.mit.edu/newsoffice/special/nobels.html" target="_blank">this MIT official source</a>
                while the thumbnails are included from <a href="http://nobelprize.org/" target="_blank">Nobelprize.org</a>.
                Here is the <a href="nobelists.js" target="_blank">Exhibit JSON data file</a>.
            </p>
        </div>
    
        <div id="top-panels">
            <table width="100%"><tr>
                <td><div ex:role="facet" ex:expression=".discipline" ex:facetLabel="Discipline"></div></td>
                <td><div ex:role="facet" ex:expression=".relationship" ex:facetLabel="Relationship"></div></td>
                <td><div ex:role="facet" ex:expression=".shared" ex:facetLabel="Shared?"></div></td>
                <td><div ex:role="facet" ex:expression=".deceased" ex:facetLabel="Deceased?"></div></td>
            </tr></table>
        </div>
        <div ex:role="viewPanel" style="padding: 1em 0.5in;">
            <table ex:role="lens" class="nobelist" style="display: none;"><tr>
                <td><img ex:src-content=".imageURL" /></td>
                <td>
                    <div ex:content=".label" class="name"></div>
                    <div>
                        <span ex:content=".discipline" class="discipline"></span>, 
                        <i ex:content=".nobel-year"></i>
                    </div>
                    <div ex:if-exists=".co-winner" class="co-winners">
                        Co-winners: <span ex:content=".co-winner"></span>
                    </div>
                    <div ex:content=".relationship-detail" class="relationship"></div>
                </td>
            </tr></table>
        
            <div ex:role="view"
                ex:viewClass="Thumbnail"
                ex:showAll="true"
                ex:orders=".discipline"
                ex:possibleOrders=".label, .last-name, .discipline, .relationship, .shared, .deceased, .nobel-year">
                <div ex:role="exhibit-lens" class="nobelist-thumbnail" style="display: none;">
                    <img ex:src-content=".imageURL" />
                    <div ex:role="exhibit-lens" ex:class-subcontent="nobelist-thumbnail {{.discipline}}"  
    				style="display: none;">
                    <div><span ex:content=".label"></span></div>
                    <div>
                        <span ex:content=".discipline" class="discipline"></span>, 
                        <span ex:content=".nobel-year" class="year"></span>
                    </div>
                </div>
            </div>
            <div ex:role="view"
                ex:label="Details"
                ex:viewClass="Tile"
                ex:showAll="true"
                ex:orders=".discipline, .nobel-year"
                ex:possibleOrders=".label, .last-name, .discipline, .relationship, .shared, .deceased, .nobel-year">
            </div>
            <div ex:role="view"
                ex:viewClass="Timeline"
                ex:start=".nobel-year"
                ex:colorKey=".discipline"
                ex:bubbleWidth="150"
                ex:bubbleHeight="150">
                <div ex:role="lens" class="nobelist-timeline-lens" style="display: none;">
                    <img ex:src-content=".imageURL" />
                    <div><span ex:content=".label"></span></div>
                    <div>
                        <span ex:content=".discipline" class="discipline"></span>, 
                        <span ex:content=".nobel-year" class="year"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </body>
</html>

**Comment by lmorillas** [comment]
Try this http://paste2.org/X7FAvULg

I don't know it it's what you want.

**Comment by jtoner** [comment]
Yes perfect - thank you for your help. greatly appreciated.

**Comment by jtoner** [comment]
Do you know the current status in regards to using a drupal backend for exhibit? Will take a look myself but just thought I would ask.

**Comment by lmorillas** [comment]
I don't know. I don't use Drupal. I have some maps  built with mediawiki/Cargo data . I'm planning a new extension this summer http://area47mil.educa.aragon.es/wiki/P%C3%A1gina_principal

Use the list better if you have got questions about Exhibit simile-widgets@googlegroups.com

**Comment by karger** [comment]
It looks like this issue has been resolved through discussion so I am closing it.
