### ISSUE TITLE
Highlighting regions on a map

### ISSUE THREAD

**Issue by camilstaps** [simile-widgets/exhibit#168]
Is it currently possible to highlight/add markers to regions on a map, instead of just lat/lng points? Would it, for example, be possible to adapt http://www.simile-widgets.org/exhibit/examples/flags/flags.html to colour each country differently?

**Comment by karger** [comment]
Yes, you can find an example here:

http://www.simile-widgets.org/exhibit3/examples/other-versions/HEAD/polymap/election08.html

We're working on updating the site to make discovering this easier.

**Comment by camilstaps** [comment]
This is great, thanks a lot.
