### ISSUE TITLE
The .labels in a Table View are no more a link to their lens

### ISSUE THREAD

**Issue by pitchke** [simile-widgets/exhibit#183]
(more background/context and test files is available at https://github.com/simile-widgets/exhibit/issues/158)

_Symptoms_ ;-)
In a Table View, you show a list of items. One column is the .label:
```
<div
	data-ex-role="view"
	data-ex-view-class="Exhibit.TabularView"
	data-ex-columns=".label, .Location, .Floor, .capacity, .RoomType"
	data-ex-column-labels="Room, Location, Floor, Capacity, Room type"
	data-ex-column-formats="item, item, list, list, list"
></div>
```
When displayed, the items with .label column (i.e. _Rooms_ here) are no more links but static text.

_Pre-diagnostic_:
A quick test shows that using the API:
src="http://api.simile-widgets.org/exhibit/STABLE/exhibit-api.js", the link works as expected
src="http://api.simile-widgets.org/exhibit/HEAD/exhibit-api.js", there is no link but static text :-(.

Thanks for your help.

**Comment by jaygray0919** [comment]
see also:
https://github.com/simile-widgets/exhibit/issues/158

**Comment by pitchke** [comment]
This is resolved by explicitly defining the type as _item_ in source files (json).
In Exhivit V2 this was implicit while in Exhibit V3 it is explicitely required of will be shown as _text_ content.
So I am closing this issue.
Thanks All.
