### ISSUE TITLE
api.simile-widgets.org is terribly slow

### ISSUE THREAD

**Issue by camilstaps** [simile-widgets/exhibit#187]
api.simile-widgets.org is replying terribly slow over here in the Netherlands on an otherwise fine internet connection. In the below screenshot, several requests take over two minutes before a 304 reply is given. This in combination with the number of requests made makes the web page load very, very slowly.

Can something be done about this?

![2017-08-23-140928_849x1040](https://user-images.githubusercontent.com/1202754/29615036-b4c49730-880c-11e7-9e90-dc9a5f096fb0.png)

**Comment by karger** [comment]
I've checked (and contacted our sysadmins) and there don't seem to be any problems at this end.  Can you confirm the problem is still happening for you?  Maybe it was ephemeral....

**Comment by camilstaps** [comment]
Odd. It happened yesterday as well, and then I waited in case it was ephemeral. But at this moment I don't experience any problems. Thanks, and apologies for bothering you.

**Comment by camilstaps** [comment]
Perhaps I was being rate-limited due to frequent reloads and `bundle=false` on the URLs. Removing that helped considerably.
