### ISSUE TITLE
Exhibit doesn't appear in https but does in http

### ISSUE THREAD

**Issue by kheatley** [simile-widgets/exhibit#191]
Not sure why the exhibit on this page (http://web.mit.edu/physics/people/faculty/index.html) works but this one doesn't (https://web.mit.edu/physics/people/faculty/index.html).

Anyone know?

**Comment by karger** [comment]
The physics exhibit has a "mixed content' problem.  The web site is 
being served over https, but it links to data at an http url.   A few 
years ago the browser vendors decided this was a security risk and set 
browsers to refuse to fetch such content.  The exhibit was created 
before this happened---it worked back then---and nobody has bothered to 
change it to keep up with the times.

If you want to avoid this problem, avoid including the protocol in your 
links.  for example, if the physics page linked to 
//api.simile-widgets.org/exhibit/3.0.0/exhibit-api.js, then the browser 
would automatically fill in the right protocol corresponding to the 
containing page.

------ Original Message ------

**Comment by karger** [comment]
It appears the problem has been fix on the mixed content page so I am closing this issue.
