### ISSUE TITLE
exhibit libs unaccessible

### ISSUE THREAD

**Issue by jaygray0919** [simile-widgets/exhibit#194]
we're seeing this message:
Failed to load resource: net::ERR_CERT_DATE_INVALID for
https://api.simile-widgets.org/exhibit/HEAD/exhibit-api.js

Our Exhibit apps are offline
Please update the certificates

**Comment by lmorillas** [comment]
It seems that the www.simile-widgets.org certificate ended yesterday
11/2/2020



-- luismiguel  (@lmorillas)

**Comment by jaygray0919** [comment]
good now - thanks
