### ISSUE TITLE
Does dat-ex-missing-label setting work?

### ISSUE THREAD

**Issue by aborruso** [simile-widgets/exhibit#91]
Hi all,
I have this facet:
```
<div data-ex-role="facet" data-ex-expression=".ente_destinatario" 
data-ex-facet-label="Ente destinatario" 
data-ex-missing-label="Dato non presente" 
data-ex-sort-mode="count">
</div>
```

But the missing label does not appear. Is it something wrong on my code?

I'm using http://api.simile-widgets.org/exhibit/current/exhibit-api.js

Thank you

**Comment by karger** [comment]
If you are still having this problem, can you send a link to an exhibit that demonstrates it?

**Comment by aborruso** [comment]
Hi @karger thank you.

Please luke here http://petrusino.opendatasicilia.it/.
In one of my facet I have applied 

"data-ex-missing-label="Non specificato"" 

but I have the generic "(missing this field)"

Is there some error on my code?

Best regards

![2015-05-02_12h57_52](https://cloud.githubusercontent.com/assets/30607/7440809/f333848a-f0ca-11e4-8182-383cfccb94fa.png)

**Comment by karger** [comment]
(missing this field) is not appearing in my copy of this exhibit.  But neither is Non specificato .  Did you fix the problem?

These kind of questions s are generally more quickly addressed on the simile-widgets.org mailing list.  It's only when a bug is confirmed that it makes more sense to shift to the issue list here.

**Comment by lmorillas** [comment]
You're mixing the "ex:"  and the "data-ex"  attributes. You should write an
uniform nominating system.


Saludos,

-- luismiguel  (@lmorillas)

2015-05-04 7:03 GMT+02:00 David Karger <notifications@github.com>:

**Comment by aborruso** [comment]
Hi @lmorillas you are right, my fault. It works thank you
